### ISSUE TITLE
Update API to new standard "Technische Anlage  V2.0"

### ISSUE THREAD

**Issue by jakob-p** [alex-therapeutics/diga-api-client#115]
## Changes

There are new specifications valid from 01.10.2023 released on 
https://www.gkv-datenaustausch.de/leistungserbringer/digitale_gesundheitsanwendungen/digitale_gesundheitsanwendungen.jsp

I noticed following changes:
- for billing XRechnung 2.2.0 is used instead of 2.0.0
- A new API to update the bills (e.g. in case the price changed for the DiGA after the first 12 months, the bills need to be updated afterwards)

Those documents have changed / are new:

[Technische Anlage für die elektronische Abrechnung der digitalen Gesundheitsanwendungen nach § 33a SGB V (elektronische Datenübermittlung) V2.0 (PDF, 213 KB)](https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/digitale_gesundheitsanwendungen/technische_anlagen_aktuell_7/DiGA_Anlage_1_Technische_Anlage_zur_RL_V2.0_20221202.pdf)

[Anhang 7 - Schlüsselverzeichnis: Gründe für Rechnungskorrekturen (PDF, 29 KB)](https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/digitale_gesundheitsanwendungen/technische_anlagen_aktuell_7/DiGA_Anhang7_Rechnungskorrekturen_V1.0.1_20221128.pdf)

[Anhang 8 - Beispiele: Umsetzung von Rechnungskorrekturen](https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/digitale_gesundheitsanwendungen/technische_anlagen_aktuell_7/DiGA_Anhang8_Rechnungskorrekturen_V1.0.0_20221205.pdf)

## Updates needed for this API Client

- **Update XRechnung to Version 2.2.0**
- Add API to update bills (Rechnungskorrekturen) 
- ?

**Comment by fongie** [comment]
Thanks for opening this issue and providing the information! Do you know when they disallow the use of the old (2.0.0) version? Or did that already happen? 😅

**Comment by jakob-p** [comment]
The changes are planned for **01.10.2023** but probably all endpoints will handle this a bit different again 😅

**Comment by jakob-p** [comment]
There is a new document that gives an example for the new requests to update (correct) already sent bills:

https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/digitale_gesundheitsanwendungen/technische_anlagen_aktuell_7/DiGA_Anhang8_Rechnungskorrekturen_V1.1.0_20230413.pdf

**Comment by rboitsg** [comment]
You can use the valid examples from this validation repository:
[https://github.com/ITSGGMBH/validator-configuration-diga/tree/xrechnung22/src/test/resources/dre0](https://github.com/ITSGGMBH/validator-configuration-diga/tree/xrechnung22/src/test/resources/dre0)

Its _xrechnung22_ branch is still in QA but should be finalized/released soon.

**Comment by fongie** [comment]
@uvinw (and others) please see discussion in https://github.com/alex-therapeutics/diga-api-client/pull/130

**Comment by jakob-p** [comment]
no, #130 only adds the update to XRechnung2.2.0 but does not contain the new API for billing updates

**Comment by fongie** [comment]
Ah yeah sorry @uvinw I missed that. The new APIs are not handled yet. Happy to review and accept PRs on the subject! Is there any API endpoint that you can test these new requests against before 1/10?

**Comment by fongie** [comment]
First beta which includes XRechnung 2.2.0 but not the updated billing APIs are in https://github.com/alex-therapeutics/diga-api-client/releases/tag/2.0.0-beta.1

**Comment by jakob-p** [comment]
@fongie  can you release the beta packages also to maven so we can import it?

**Comment by fongie** [comment]
Woops, our release workflows were failing. I fixed them, so the github one works (you can get it here https://github.com/alex-therapeutics/diga-api-client/packages/666222 ) but the maven one failed to sign with gpg for some reason. Im looking into fixing that

**Comment by fongie** [comment]
All good now, 2.0.0-beta.1 is up on maven :) @jakob-p

**Comment by sallner** [comment]
Ahoi, it seems that the testing infrastructure is not running with XRechnung 2.0 but only XRechnung 2.2. Will there be a non-beta release for the 2.0 version of this package? I would like to promote a new released version into https://github.com/gtuk/diga-api-service.

**Comment by fongie** [comment]
Hi @sallner ! Do you have any updates on how the new billing API is working? Is it implemented by the insurances yet? My understanding was that this should've been done by now. In that case, for a stable 2.0 release, I would be waiting for:
- a PR to support the new billing api changes
- confirmation that the new XRechnung 2.2.0 changes implemented in the beta release are working (did anyone check yet?)

do you have any information on this? I would consider releasing a stable version without the billing changes if it seems like everything except the new billing features as well

**Comment by michaelmerg** [comment]
It looks like some insurances already using the new version 2.2.0. I'm seeing error when calling the Billing API for insurances using the Bitmark infra and from TK. Both work fine using the 2.0-beta.1 version.

**Comment by fongie** [comment]
Okay! It sounds like it might be useful to release 2.0.0 as stable even if we dont include the new billing api changes (?), what do you guys think?

**Comment by jakob-p** [comment]
6 / 8 Endpoints now accept the new XRechnung 2.2.0 from the beta, 
only arge.da-api.aok.de and diga.apimisc.de did not switch yet...

I'd say we can release this as 2.0.0 stable

**Comment by jakob-p** [comment]
we should note in the changelog that now Java 17 is required. 
You dont notice it when validating the DiGA testcode, but for other codes the POM Artifact
 [Base32Check Java 0.1.0](https://github.com/bitmarck-service/base32check-java/releases/tag/0.1.0) will crash with Java 11

**Comment by fongie** [comment]
I have released 2.0.0 as stable now as discussed, breaking change is the update to java 17. Thanks a lot @jakob-p for doing the work on adapting to xrechnung 2.2.0 :)

this issue remains open until we support the new billing api features (renewing subscriptions etc)

**Comment by sallner** [comment]
Thanks for the release @fongie.

**Comment by fongie** [comment]
Corrections are now live in`2.1.0` after @gtuk s contribution here #154 ! Closing this. Feel free to reopen or open a new issue if there are more features missing relating to this
