### ISSUE TITLE
Up Java version to 17

### ISSUE THREAD

**Issue by fongie** [alex-therapeutics/diga-api-client#141]
## Problem

__we should note in the changelog that now Java 17 is required. 
You dont notice it when validating the DiGA testcode, but for other codes the
 [Base32Check Java 0.1.0](https://github.com/bitmarck-service/base32check-java/releases/tag/0.1.0) will crash with Java 11__

_Originally posted by @jakob-p in https://github.com/alex-therapeutics/diga-api-client/issues/115#issuecomment-1786915195_
            

## Solution

Describe how you are going to implement it, or "dont know" if you don't know yet.

**Comment by jakob-p** [comment]
When trying to validate the Code DIGACODE12345678 with Java 11 i get this error:

**java.lang.UnsupportedClassVersionError: de/bitmarck/bms/base32/Base32Check1 has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0**

on Java 17 i get the correct error message

**Invalid DiGA code**
