### ISSUE TITLE
Endpoint diga.apimisc.de requires the contentType to be set for the encrypted data in the Multipart requests

### ISSUE THREAD

**Issue by ZMH3G** [alex-therapeutics/diga-api-client#147]
## Problem

Since last week no DiGA codes can be validated or bills be sent to the endpoint **diga.apimisc.de** as they installed an update and now the Multipart requests require the MediaType to be set for the encrypted xml content (nutzdaten).

## Solution

Set the MediaType of the encrypted content of the multipart request to "application/octet-stream".
I tested this and it fixes the issue for the endpoint diga.apimisc.de while the other also accept it for the test code validation.

**Comment by fongie** [comment]
released in `2.0.1`, thanks for the contribution!

**Comment by jakob-p** [comment]
thank you for the fast release 🚀
