### ISSUE TITLE
Ensure you cannot send test codes to validate method

### ISSUE THREAD

**Issue by fongie** [alex-therapeutics/diga-api-client#15]
## Problem

In DigaApiClient->validateDigaCode method, you can input a test code and receive a "success" reply. Potentially a customer could input a test code into the DiGA and get access without a proper code that way.

## Solution

Make a check at the start of the method to see if it is a test code (use DigaUtils method for this), and if it is, throw an exception OR build a response containing a custom error ("test code sent to real code validation" or something)

**Comment by AlexS968** [comment]
Hi @fongie, i fixed the issue...
