### ISSUE TITLE
Create documentation on the verification process of prescription codes

### ISSUE THREAD

**Issue by SebastianRehfeldt** [alex-therapeutics/diga-api-client#51]
First of all, thanks a lot for creating this repository! We at [xbird](https://xbird.io/) just started to explore how we can verify the diga prescription codes and are very happy that you are sharing both your code and information about it.

## Problem

From the official documentation it is hard to figure out how requests can be sent to verify prescription codes. There is an openapi definition of the [diga endpoint](https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/digitale_gesundheitsanwendungen/technische_anlagen_aktuell_7/digaSP_1_0_05.yaml) but it is not obvious how the request and the response data should look like. (Billing is also not clear but probably deserves it's own documentation/issue)

## Solution

It would be great to have a documentation which includes:
- high-level information about how the prescription code can be verified and used for billing
- how the request data for billing and verification must look like, ideally with some examples of the `nutzdaten` before encryption and encoding
  - also how the decrypted `nutzdaten` response looks like
- how `nutzdaten` can be encrypted/decrypted
- how insurance information can be extracted from the mapping file based on the prescription code
- how fields like diga manufacturer id should look like in test requests when the diga is not approved yet and therefore the id is still unknown
  - similar for the diga manufacturer IK number = `iksender`

I'd be up for writing down my current understanding of the diga verification api and creating a PR to this repository. Could be some markdown files within a `docs` folder or as wiki pages. Not sure though if it's also in your interest to collect documentation in this repository or just the code for the api client :)

**Comment by fongie** [comment]
Hi @SebastianRehfeldt ! 

I understand what you mean, the information is still really scarce (and it was even worse before). When building this, I was intending to write a blog post about what I learned about these things, but other stuff got in the way...

In case you haven't figured everything out yet, you can find the answers to your questions by looking at the source code for this library or by running some test requests in debug mode and inspecting what comes out. The library has been shown to work in production for a few of the APIs by now thanks to @gtuk who also fixed several things we couldn't catch with test requests, so it is getting to a more reliable stage.

I think I like the idea to gather information and documentation about the DiGA API in this repository if you wish to contribute to that. I've already written some things in the Wiki here and ideally I would like to continue using the Wiki but it is my understanding that you cannot make pull requests against it, so maybe a 'doc' folder with markdown is better. What do you think?

By the way, are you intending to use this client or are you writing your own?

**Comment by SebastianRehfeldt** [comment]
Hi @fongie,
We are not sure yet if we want to use this client or write our own solution (most likely in Python and with a first focus on code verification). We are no Java developers and cannot really integrate the client as it is right now. A docker container which exposes the verification/billing logic via an api could be a solution though :) This also seems to align with your long term ideas and plans for this repository as far as I can see from your Readme?

In any way, contributing to this repository with documentation makes sense to us. Based on a more detailed documentation, it will also be easier to build solutions in other languages. Regarding the wiki, I also doubt that we can open Pull Requests. Therefore, I'd go with a `doc` folder. To avoid building and publishing a new version of the client, we could also close the PR once it is accepted and transfer the content to the wiki. Would that work for you as well?

**Comment by fongie** [comment]
We only build & release on creating a "github release" to keep some control of the releases, so it is no problem to merge doc requests to master. But I still think the second option is best to keep the "general" documentation separate from the source code of the library, so let's try that. When you (or someone else) make a doc PR, I will transfer that to the wiki and close the PR with a link to the new wiki page, or the old one that was updated.

Regarding the docker container, yes, that is a long-term idea and something I thought of to help people like yourself who can't use it as a java library, but unfortunately I don't have time to do it myself right now. Perhaps we can make some progress there during the summer as it shouldn't be too hard but I can't promise anything. It would be nice though 😄

**Comment by SebastianRehfeldt** [comment]
Ok sounds good! I'll try to work on the documentation this week and keep you posted :)

And yes the docker container would be amazing! Although there are some things which might get a bit tricky. Ideally we would like to have some control about the logging or define how to handle eventual problems with billing etc. Nothing impossible though. Depending on whether we want to integrate the client or write something ourselves, we might create another issue for the docker container.

**Comment by SebastianRehfeldt** [comment]
> By the way, are you intending to use this client or are you writing your own?

Regarding your initial question: seeing how much effort you already put into this and seeing that it gets stable, we'd like to integrate this client instead of writing our own. We are currently exploring options how to best integrate it into our system. The probably best and most universal solution would be to wrap the client into an api and put it into docker. As already said, we are no Java developers but would like to give it a try. More likely we will write the server in Kotlin but lets see :)

I think it would be cleanest to create a fresh repository for the server and leave this repository for the package and documentation only. I can also ping you once we have some more concrete plans for the server. What do you think? :)

**Comment by gtuk** [comment]
I had some spare time yesterday and quickly hacked a small kotlin api around the client. https://github.com/gtuk/diga-api-service
Maybe it is already useful like this, if you have questions let me know. I will continue working and improving the service in the upcoming weeks

**Comment by SebastianRehfeldt** [comment]
That looks great @gtuk ! Thanks a lot :)

**Comment by fongie** [comment]
Wow that was quick @gtuk , great job! I will watch the repository and give it a little bit of time to be tested by @SebastianRehfeldt and co, then add a link to it in the readme in this repo 😄

**Comment by SebastianRehfeldt** [comment]
We will definitely give it a try as soon as we have all the prerequisites, like IK number and certificate from ITSG, ready and let you guys know :)

I have a general comment regarding one of the TODOs from @gtuk : `More validation`.

Is that related to code validation in general, e.g. validating the checksum or used characters in the code? Then I guess this is something which could directly go to the client into this repository? What do you think? Also there is some utils functionality to check if the code is within the provided DiGA test codes. Just in case we have some time to contribute, we could maybe discuss where we want to put these things. As that might also go directly to the client.

**Comment by gtuk** [comment]
I would totally agree that validation of the code should be inside the client instead of my api wrapper (there is actually already a small validation in the client -> https://github.com/alex-therapeutics/diga-api-client/blob/7a8ac66edc6be9397e8c5db40ba36af3ff0c2f7a/src/main/java/com/alextherapeutics/diga/implementation/DigaCodeDefaultParser.java#L95).
Inside our production api wrapper we additionally use https://github.com/bitmarck-service/base32check-java to validate the code. There is already an open issue here https://github.com/alex-therapeutics/diga-api-client/issues/24 and I am planning to create a PR for this in the upcoming weeks if @fongie is not already working on it

**Comment by fongie** [comment]
I am not already working on it, so I would be very happy for a PR including that functionality 🚀

**Comment by fongie** [comment]
closed in #54
