### ISSUE TITLE
Provide a dockerized environment for development

### ISSUE THREAD

**Issue by bokchan** [alex-therapeutics/diga-api-client#53]
## Problem

I had issues getting the project to compile on my local machine (ubuntu 20.04). Mainly because I because I am java noob. 

It could be helpful to have provide a dockerized environment to make it easier to get started. 

## Solution

As I couldn't get it to work I created a dev setup using `docker-compose`. I'd be happy to a pull request if you feel it could be useful for others. 

The branch is: https://github.com/bokchan/diga-api-client/tree/set-up-docker-compose-dev-env

Added a how-to: https://github.com/bokchan/diga-api-client/blob/set-up-docker-compose-dev-env/DEVELOPMENT.md

Full disclosure! I also work as a developer at xbird.io, together with [@SebastianRehfelt](https://github.com/SebastianRehfeldt) who created #51

**Comment by fongie** [comment]
Hi @bokchan ! Thanks for opening the issue and doing some work on the dev environment 😄 

I am not sure about pulling this into the main repository, though. I think most java developers are using a full-blown Java IDE like IntelliJ, Eclipse, etc., and then it is not so useful to have this option for VSCode.

I will keep this issue open so other people can chime in if they want this too - you can write a comment or add a thumbs up 👍  to the issue. If not, this will probably be a no-go.

Thanks for contributing and don't hesitate to open other issues!

**Comment by fongie** [comment]
Closing as there's been no further interest
