### ISSUE TITLE
diga.apimisc.de expects other headers and transfer type

### ISSUE THREAD

**Issue by fongie** [alex-therapeutics/diga-api-client#65]
## Problem

diga.apimisc.de is not responding to requests right now (although our endpoints status document suggests it used to?)

A lot of troubleshooting by the team at Rehappy (@SandraHicks) suggests that this endpoint works differently from other endpoints: it requires the request body to be sent as a single chunk (not streamed), and that it requires the Content-Length header

Right now I'm not sure this is why our library is failing to reach this endpoint but this should be looked into

## Solution

Find out how to configure these parameters with OkHttp and see if we get a request working against this endpoint. If it does, add logic to send the correctly configured request when the apimisc endpoint is used

**Comment by jakob-p** [comment]
diga.apimisc.de is working for us at the moment,  is it still failing?

**Comment by fongie** [comment]
> diga.apimisc.de is working for us at the moment, is it still failing?

thats interesting and good news! I havent had the chance to work on this yet. are both test and real requests working for you using the library?

**Comment by jakob-p** [comment]
We did only make test requests so far, but those are working with our certificate

**Comment by jakob-p** [comment]
Might be a certificate issue, that they locked out the certificates issued by the older root CA from ITSG. But just a wild guess.

**Comment by jakob-p** [comment]
We didn't get a new certificate, the Endpoint needs to accept certificates issued from both the old and the new CA (old one is still valid until 2025).

So if the old certificates don't work, you'll need to contact them (address can be found in Krankenkassenverzeichnis.xml)

**Comment by jakob-p** [comment]
I also tested sending the test bill to and insurance using diga.apimisc.de (Kostentraegerkuerzel C4) and it worked, so i dont think this is an issue with this library

**Comment by fongie** [comment]
Thanks for your help @jakob-p !
