### ISSUE TITLE
5 out 8 endpoints fail

### ISSUE THREAD

**Issue by kennyx46** [alex-therapeutics/diga-api-client#66]
Thanks a lot for the work invested to create and publish this library.
## Problem

We received the certificate from ITSG a week ago (Jan 20). During the last week, we tried to implement the DIGA communication solution using your library (for now only for testing codes validation). Unfortunately, 5 out of 8 endpoints still do not work for us. It is worth mentioning the errors we receive vary depending on the endpoint:

1. `diga.bitmarck-daten.de` - javax.net.ssl.SSLException: readHandshakeRecord caused by java.net.SocketException: Broken pipe
2. `diga-api.tk.de/diga/api/public/rest` - javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
3. `itscare.da-api.aok.de` - javax.net.ssl.SSLException: Tag mismatch! Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
4. `diga.apimisc.de` - java.net.ProtocolException: expected the Content-Type to have a boundary parameter
5. `arge.da-api.aok.de` - java.net.ProtocolException: expected the Content-Type to have a boundary parameter
6. `diga.kkh.de` - works
7. `da-api.gkvi.de` - works
8. `kubus-it.da-api.aok.de` - works

The first three errors seem to be related to the certificates. So I wonder whether this is just a timing issue (e.g the endpoints are still not updated with the new keys) and we need to wait for a few more days/weeks. Could you please share your experience in this regard? Did it work for you right away or does it take some time?

Two next errors (4,5) seem to be similar to https://github.com/alex-therapeutics/diga-api-client/issues/62. Unfortunately from the thread in that issue, it is not fully clear to me whether it is a timing issue as well or whether some steps from our side are needed.

Considering the 3 last endpoints (6, 7, 8) work for us it seems the problem might not be on our side, not sure though.

Have you seen anything similar? How often do you check whether the endpoints work?

Would be grateful for your assistance.

## Solution

no solution

**Comment by fongie** [comment]
Hi @kennyx46 thanks for opening an issue!

We've had other issues opened in the past on this subject which seems to have been solved by simply waiting for the insurances or itsg to accept your key, see for example https://github.com/alex-therapeutics/diga-api-client/issues/64

However, we probably have a problem with apimisc see https://github.com/alex-therapeutics/diga-api-client/issues/65 which we will look into

I can test the other endpoints you have problems with next week, but I tried bitmarck (which has the majority of companies connected with it) earlier this week and it worked no problem, so most likely your issue with the endpoints (other than apimisc) has to do with them not recognizing your key yet. I know the error messages can be confusing but unfortunately it's been clear from the beginning that the different endpoints behave quite differently in general

I suggest you try again in a week or so and I will also try some of the endpoints to see how they respond and comment here what I find out

**Comment by kennyx46** [comment]
Thanks a lot for your answers. So after almost two weeks, 6 out of 8 endpoints started working 
(`diga-api.tk.de/diga/api/public/rest` fails from time to time though).
The two not working are:
1. `diga.bitmarck-daten.de`
2. `diga.apimisc.de`

Will try to notify them then.

**Comment by fongie** [comment]
Thank you for clearing this up @jakob-p ! I will close this issue, since it doesn't seem like an issue with the library. Feel free to reopen if you disagree.
