### ISSUE TITLE
arge.da-api.aok.de returns request data invalid

### ISSUE THREAD

**Issue by fongie** [alex-therapeutics/diga-api-client#7]
## Problem

Both test and "real" requests return request/xml data invalid errors. "Real" requests actually return this error twice (2 "errors" are returned in the XML). This suggests that one of the errors is the "wrong check character" error that we are getting for most requests, but the other error is some bug with our/their implementation

## Solution

Don't know

**Comment by gtuk** [comment]
Problem is not happening anymore with the latest version of the library #55
